[package]
name = "conduitrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = {version = "0.5.7", features = ["serde_json"]}
diesel = {version="1.4.8", features =["sqlite", "chrono", "uuid"]}
